### PR TITLE
Adds  a how-to document on email groups

### LINKED ISSUE #17: Create a document to describe the Google Groups specifics/how-to
https://github.com/InnerSourceCommons/foundation-governance/tree/master/how-to.  The file should explain how mailing lists work in the InnerSource Commons:

- How to request a new mailing list
- How to get added to a mailing list
- What mailing lists are out there, and what are they for
- How to interact with a mailing list

### PR DESCRIPTION
**Pull request by andrea-kyurchiev**
Closes #17

### CODE REVIEW

**Review by rrrutledge — CHANGES_REQUESTED** [review]
Thank you for this work!  Can you double-check that this description meets all of the points described in https://github.com/InnerSourceCommons/foundation-governance/issues/17?  Thank you!

**Comment by rrrutledge** [comment]
> added the currently existing groups

Is there no way to see those in the Google Groups UI or anything?

**Comment by andrea-kyurchiev** [comment]
They can be seen and managed from: https://admin.google.com/u/1/ac/groups and users within the organisation can see them in https://groups.google.com/u/1/all-groups (unless the group privacy says they can't)

**Comment by rrrutledge** [comment]
Can people outside the organization see them?

**Comment by andrea-kyurchiev** [comment]
No, they're internal. Only people added to them from outside the organisation will be able to see them

**Comment by rrrutledge** [comment]
OK - I will think about this.

**Review by rrrutledge — APPROVED** [review]
This is better than what we have now.

**Pull request merged**
